name: Task
description: Track a small task or chore
title: "[Task] "
labels: ["task"]

body:
- type: textarea
  attributes:
    label: What
    description: What should be done?
  validations:
    required: true

- type: textarea
  attributes:
    label: Notes
    description: Add any context, links, or constraints if needed.

- type: textarea
  attributes:
    label: Done when
    description: What conditions should be met before this is done?
    value: |
      - [ ] 
